# Site Settings
title: 空
email: 641570479@qq.com
description: 空.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://githubnull.github.io" # the base hostname & protocol for your site
google_analytics: "UA-83979019-1"

# User Settings
username: 空
user_description: 空.
disqus_username: 空

# Social Media
# Remove the item if you don't need it
github_username: githubnull

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主页
    url: /
  - title: 关于
    url: /about/
  - title: 联系
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
